config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'search/create'
  get 'search/create1'
  get 'main/login'

  resources :models

end

app/models/model.rb
class Model < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
  def login

  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    @models = Model.all
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:fecha, :nemo, :volumen_total, :rotacion_mensual, :nuemro_ops)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def create
    palabra = "%#{params[:keyword]}%"

    @models = Model.where('nemo LIKE ?', palabra)

    respond_to do |format|
      format.html { redirect_to root_path}
      format.json {render json: @models}
      format.js
    end
  end
  def create1
    palabra = "%#{params[:keyword]}%"

    @models = Model.where('fecha LIKE ?', palabra)


    respond_to do |format|
      format.html { redirect_to root_path}
      format.json {render json: @models}
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DEMO Reportes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body>
<%= render partial: 'shared/navbar' %>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<div class="row">
  <div class="col-sm-3">
    <div class="sidebar-nav">
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="visible-xs navbar-brand">Sidebar menu</span>
        </div>
        <div class="navbar-collapse collapse sidebar-navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Consulta', models_path%></li>
            <li><%= link_to 'Consulta dinamica', root_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>

                <li class="divider"></li>
                <li class="dropdown-header">Sub menu</li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Action</a></li>
              </ul>
            </li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <div class="col-sm-9">
    <div align="center" class="container">
      <%= form_tag({controller: "search", action: "create" }, method: 'get', remote: true, id: "search-form") do %>
          <h1 >
            REPORTE
          </h1>
          <div>
            <strong>Nemo: </strong><%= text_field_tag :keyword, nil, placeholder: 'Nemo',
             :size => 40 %>
            <%= content_tag :button, type: :submit do%>
                Buscar
            <% end %>
          </div>


      <% end %>


      <!--Formulario fecha -->

      <%= form_tag({controller: "search", action: "create1" }, method: 'get', remote: true, id: "search-form") do %>

          <div>
            <strong>Fecha: </strong><%= text_field_tag :keyword, nil, placeholder: '2017-01-01',
                                                    :size => 40 %>
            <%= content_tag :button, type: :submit do%>
                Buscar
            <% end %>
          </div>

      <% end %>

    </div>
    <hr>




    <div id="resulados">
    </div>
  </div>
</div>

app/views/main/login.html.erb
<div class="wrapper">
  <form class="form-signin">
    <h2 class="form-signin-heading">Please login</h2>
    <input type="text" class="form-control" name="username" placeholder="Email Address" required="" autofocus="" />
    <input type="password" class="form-control" name="password" placeholder="Password" required=""/>
    <label class="checkbox">
      <input type="checkbox" value="remember-me" id="rememberMe" name="rememberMe"> Remember me
    </label>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
  </form>
</div>

app/views/models/_form.html.erb
<%= form_for(@model) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :nemo %><br>
    <%= f.text_field :nemo %>
  </div>
  <div class="field">
    <%= f.label :volumen_total %><br>
    <%= f.number_field :volumen_total %>
  </div>
  <div class="field">
    <%= f.label :rotacion_mensual %><br>
    <%= f.text_field :rotacion_mensual %>
  </div>
  <div class="field">
    <%= f.label :nuemro_ops %><br>
    <%= f.text_field :nuemro_ops %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/models/_model.html.erb
<div class="container">
  <table class="table table-striped">
    <thead >
    <tr>
      <th width="100">Fecha</th>
      <th width="120">Nemo</th>
      <th width="120">Volumen total</th>
      <th width="100">Rotacion Mensual</th>
      <th width="80">Numero de OPS</th>
    </tr>
    </thead>

    <tbody>
    <tr>
      <td><%= model.fecha %></td>
      <td><%= model.nemo  %></td>
      <td><%= model.volumen_total %></td>
      <td><%= model.rotacion_mensual %></td>
      <td><%= model.nuemro_ops %></td>
    </tr>

    </tbody>
  </table>
   <%=bar_chart @models.group(:nemo).sum(:rotacion_mensual) %>
  <%= pie_chart @models.group(:nemo).count %>



</div>

app/views/models/edit.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>


<div class="row">
  <div class="col-sm-3">
    <div class="sidebar-nav">
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="visible-xs navbar-brand">Sidebar menu</span>
        </div>
        <div class="navbar-collapse collapse sidebar-navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Consulta', models_path%></li>
            <li><%= link_to 'Consulta dinamica', root_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>

                <li class="divider"></li>
                <li class="dropdown-header">Sub menu</li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Action</a></li>
              </ul>
            </li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <div class="col-sm-9">

    <div class="container">
      <h1>Editar</h1>

      <%= render 'form' %>

      <%= link_to 'Ver', @model %> |
      <%= link_to 'Volver', models_path %>
    </div>





  </div>



</div>
</div>

app/views/models/index.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>


<div class="row">
  <div class="col-sm-3">
    <div class="sidebar-nav">
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="visible-xs navbar-brand">Sidebar menu</span>
        </div>
        <div class="navbar-collapse collapse sidebar-navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Consulta', models_path%></li>
            <li><%= link_to 'Consulta dinamica', root_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>

                <li class="divider"></li>
                <li class="dropdown-header">Sub menu</li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Action</a></li>
              </ul>
            </li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <div class="col-sm-9">


    <p id="notice"><%= notice %></p>
    <div class="container" align="center">
      <h1>Consulta estatica</h1>
      <p><%= link_to 'Reporte Dinamico', root_path, class: "btn btn-primary btn-lg" %> </p>
      <%= link_to 'Nuevo', new_model_path %>
      <table class="table table-striped">
        <thead >
        <tr>
          <th>Fecha</th>
          <th>Nemo</th>
          <th>Volumen total</th>
          <th>Rotacion mensual</th>
          <th>Numero ops</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @models.each do |model| %>
            <tr>
              <td><%= model.fecha %></td>
              <td><%= model.nemo %></td>
              <td><%= model.volumen_total %></td>
              <td><%= model.rotacion_mensual %></td>
              <td><%= model.nuemro_ops %></td>
              <td><%= link_to 'Ver', model %></td>
              <td><%= link_to 'Editar', edit_model_path(model) %></td>
              <td><%= link_to 'Eliminar', model, method: :delete, data: { confirm: 'Seguro desea Eliminar?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <br>

      <%= bar_chart Model.group(:nemo).sum(:volumen_total) %>


      <%= line_chart Model.group(:volumen_total).count %>
      <%= pie_chart Model.group(:nemo).count %>



    </div>



  </div>
</div>

app/views/models/new.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>


<div class="row">
  <div class="col-sm-3">
    <div class="sidebar-nav">
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="visible-xs navbar-brand">Sidebar menu</span>
        </div>
        <div class="navbar-collapse collapse sidebar-navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Consulta', models_path%></li>
            <li><%= link_to 'Consulta dinamica', root_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>

                <li class="divider"></li>
                <li class="dropdown-header">Sub menu</li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Action</a></li>
              </ul>
            </li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <div class="col-sm-9">

    <div class="container">
      <h1>Nuevo</h1>

      <%= render 'form' %>

      <%= link_to 'Volver', models_path %>
    </div>





  </div>



  </div>
</div>

app/views/models/show.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>


<div class="row">
  <div class="col-sm-3">
    <div class="sidebar-nav">
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="visible-xs navbar-brand">Sidebar menu</span>
        </div>
        <div class="navbar-collapse collapse sidebar-navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Consulta', models_path%></li>
            <li><%= link_to 'Consulta dinamica', root_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>

                <li class="divider"></li>
                <li class="dropdown-header">Sub menu</li>
                <li><a href="#">Action</a></li>
                <li><a href="#">Action</a></li>
              </ul>
            </li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  <div class="col-sm-9">

    <div class="container">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Fecha:</strong>
        <%= @model.fecha %>
      </p>

      <p>
        <strong>Nemo:</strong>
        <%= @model.nemo %>
      </p>

      <p>
        <strong>Volumen total:</strong>
        <%= @model.volumen_total %>
      </p>

      <p>
        <strong>Rotacion mensual:</strong>
        <%= @model.rotacion_mensual %>
      </p>

      <p>
        <strong>Nuemro ops:</strong>
        <%= @model.nuemro_ops %>
      </p>

      <%= link_to 'Editar', edit_model_path(@model) %> |
      <%= link_to 'Volver', models_path %>


    </div>





  </div>



</div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <%= image_tag "logo.png", :alt => "Logo", :title => "Logo", :width => "280px", :height => "60px" %>

    <ul class="nav navbar-nav navbar-right">

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Nombre Empresa <b class="caret"></b></a>
        <ul class="dropdown-menu">

          <li class="divider"></li>
          <li>
            <a href="login.html"><i class="fa fa-fw fa-power-off"></i> Cerrar sesión</a>
          </li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--
<ul class="nav nav-pills">
  <li role="presentation" class="active"><a href="#">Home</a></li>
  <li role="presentation"><a href="#">Profile</a></li>
  <li role="presentation"><a href="#">Messages</a></li>
</ul>
-->



<!-- Image and text
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand" href="#">
    <img src="/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
    Bootstrap
  </a>
</nav>
-->